steps:
  - name: 'maven:3-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: [ 'test' ]
  - name: gcr.io/cloud-builders/gcloud
    args: [ 'functions',
            'deploy',
            '${REPO_NAME}',
            '--runtime=java21',
            '--region=europe-west1',
            '--source=.' ]